output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = module.eks.cluster_endpoint
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "vpc_id" {
  value = module.vpc.vpc_id
}

output "subnet_0" {
  value = element(module.vpc.private_subnets, 0)
}

output "subnet_1" {
  value = element(module.vpc.private_subnets, 1)
}